app = "0x77-mc"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[statics]]
guest_path = "/public"
url_prefix = "/"

[mounts]
source = "minecraft_data"
destination = "/data"

[[services]]
http_checks = []
internal_port = 25565
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 25565

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
